export const SET_SELECTED_RASTE_FOR_ADD_CENTER = "SET_SELECTED_RASTE_FOR_ADD_CENTER";
export const CLEAR_SELECTED_RASTE_FOR_ADD_CENTER = "CLEAR_SELECTED_RASTE_FOR_ADD_CENTER";
export const ERR_FOR_SELECTED_RASTE_IN_ADD_CENTER = "لطفاً یک رسته انتخاب کنید";

export const SET_SELECTED_PARISH_FOR_ADD_CENTER = "SET_SELECTED_PARISH_FOR_ADD_CENTER";
export const CLEAR_SELECTED_PARISH_FOR_ADD_CENTER = "CLEAR_SELECTED_PARISH_FOR_ADD_CENTER";
export const ERR_FOR_SELECTED_PARISH_IN_ADD_CENTER = "لطفاً یک محله انتخاب کنید";

export const CLEAR_ADD_CENTER_FORM = "CLEAR_ADD_CENTER_FORM";

export const SUBMIT_ADD_CENTER_FORM = "SUBMIT_ADD_CENTER_FORM";
