export const GET_REPORTS = "GET_REPORTS",
  REPORTS_LOAD = "REPORTS_LOAD",
  SELECTED_REPORT = "SELECTED_REPORT",
  GET_REPORTS_ERR = "GET_REPORTS_ERR",
  CLEAN_REPORTS = "CLEAN_REPORTS",
  ADD_REPORT_LOAD = "ADD_REPORT_LOAD",
  ADD_REPORT = "ADD_REPORT";
